variable "vbond_ami" {}
variable "viptela_instances_type" {}
variable "region" {}
variable "common_tags" {}
variable "sdwan_cp_sg_id" {}
variable "counter" {}
variable "mgmt_subnets" {}
variable "public_subnets" {}
variable "ssh_pubkey_file" {}
variable "sdwan_org" {}