variable "vsmart_ami" {}
variable "vsmart_day0" {}
variable "viptela_instances_type" {}
variable "region" {}
variable "common_tags" {}
variable "sdwan_cp_sg_id" {}
variable "counter" {}
variable "mgmt_subnets" {}
variable "public_subnets" {}
variable "enable_eip_mgmt" {}
variable "ssh_pubkey" {}
variable "sdwan_org" {}
variable "route53_zone" {}
