variable "vsmart_image" {}
variable "viptela_instances_type" {}
variable "region" {}
variable "Vipela_Control_Plane" {}
variable "counter" {}
variable "subnet" {}
variable "resource_group_name" {}
variable "username" {}
variable "password" {}
variable "avsetvsmart" {}